In [25]:
import tensorflow as tf
import numpy as np

In [23]:
input = tf.Variable([1,2], dtype=tf.float32, name="input")
print(input)

<tf.Variable 'input:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>


In [13]:
activs = tf.zeros((3,2), dtype=tf.float32, name="activs")
print(activs)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [47]:
activs = tf.tensor_scatter_nd_update(activs, [[0,0],[0,1]], input)

In [54]:
tf.constant([[0,0],[0,1],[1,0]])

<tf.Tensor: id=118, shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 1],
       [1, 0]], dtype=int32)>

In [56]:
activs.shape

TensorShape([3, 2])

In [53]:
tf.constant(np.column_stack((np.full((3), 0), np.arange(3))), dtype=tf.int32)

<tf.Tensor: id=116, shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 1],
       [0, 2]], dtype=int32)>

In [15]:
print(activs)

tf.Tensor(
[[1. 2.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [16]:
n1 = tf.constant([[0, 0], [0, 1], [1,0]], dtype=tf.int32, name="links")
print(n1)

tf.Tensor(
[[0 0]
 [0 1]
 [1 0]], shape=(3, 2), dtype=int32)


In [17]:
x=tf.gather_nd(activs, n1, name="x")
print(x)

tf.Tensor([1. 2. 0.], shape=(3,), dtype=float32)


In [18]:
w=tf.constant([3,2,2], dtype=tf.float32, name="w")
print(w)

tf.Tensor([3. 2. 2.], shape=(3,), dtype=float32)


In [19]:
tf.nn.sigmoid(tf.tensordot(x, w, axes=1), name="node_out")

<tf.Tensor: id=77, shape=(), dtype=float32, numpy=0.999089>

In [20]:
n1 = tf.SparseTensor(indices=[[0, 0], [0, 1]], values=[1, 2], dense_shape=[3, 2])
print(n1)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 2], shape=(2,), dtype=int64))
